const WS_IN = {
  CREATE_CONVERSATION: "CREATE_CONVERSATION",
  JOIN: "JOIN",
  MESSAGE: "MESSAGE",
  VIEW: "VIEW",
};

const WS_OUT = {
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  JOIN_SUCCESS: "JOIN_SUCCESS",
  JOIN_REFUSED: "JOIN_REFUSED",
  NEW_MESSAGE: "NEW_MESSAGE",
  HISTORY: "HISTORY",
  ERROR: "ERROR",
  SYSTEM: "SYSTEM",
};

const CHAT_TYPE = {
  PRIVATE: "private",
  GROUP: "group",
};

module.exports = { WS_IN, WS_OUT, CHAT_TYPE };
