const WS_IN = {
  CREATE_CONVERSATION: "CREATE_CONVERSATION",
  JOIN: "JOIN",
  MESSAGE: "MESSAGE",
  VIEW: "VIEW",
  PING: "PING",
};

const WS_OUT = {
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  JOIN_SUCCESS: "JOIN_SUCCESS",
  JOIN_REFUSED: "JOIN_REFUSED",
  MESSAGE_SENT: "MESSAGE_SENT",
  NEW_MESSAGE: "NEW_MESSAGE",
  HISTORY: "HISTORY",
  ERROR: "ERROR",
  SYSTEM: "SYSTEM",
};

const CHAT_TYPE = {
  PRIVATE: "private",
  GROUP: "group",
};

const ERROR_TYPE = {
  DUPLICATE_KEY: 11000,
};

const MESSAGE_STATUS = {
  SENDING: "sending",
  SENT: "sent",
  RETRYING: "retrying",
  FAILED: "failed",
};

const PRESENCE_TTL = 10;

module.exports = {
  WS_IN,
  WS_OUT,
  CHAT_TYPE,
  ERROR_TYPE,
  MESSAGE_STATUS,
  PRESENCE_TTL,
};
